### ISSUE TITLE
when run from gitlab CI, mypy does not use virtual environment

### ISSUE THREAD

**Issue by dpinol** [tox-dev/pre-commit-uv#61]
Hi,
replacing pre-commit with pre-commit-uv on our development machines our  "pre-commit run --all mypy" has the same behaviour as with default pre-commit.
However, when running on gitlab CI, it looks like pre-commit is not creating a separate virtualenv with the dependencies on the "additional_dependencies" field, but it's running on the outer environment.

does it make any sense?

thanks

```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: (bin)
        additional_dependencies:
          - deepdiff~=8.5.0

```
